language: java
install: gradle -v build
script: gradle build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VCvrzkhwBNMgO+EJiQ0uRmUP4rsupdeRQ1fAJV2gJB/0pOauygrXBv9AMVLCZWN5JzytzuMj+vfWZKLD4HlugPR/GBmBOfpBBQxsSSOCzvNd7avrgdY559TGaw4SaGhx8x37rbNXV8JISgm2PAUwpbV8azql/NSuWqDDwqkmhgyn8AXmh/s+a1swnf7Aa+65NMWsh1GDKrPDgfe1mM/ol3AZ/MVBjaJYorz2izktd0WoB5RHrDWocR0KJ9lg+DpfgSuLwakFkbc2S1j3T+pRIOI7sP4QZxmnT1NHELt8QCPrRvUYrFSkge/AhVZ98XwjO63MamVNyg94cYueGQ2RE9ky7e5yAFwt3Wl7AJi4BYi3qLHkIfLZDdj5GzPu8DGDXmgovpkGJQYzYQEFItDWic5T6bDjZA47DtrFQTdkGe1emXV2wLeyp795N0OO4AGry/qtkfoBF4i5ZUXGEjQcdij/g7m+Hda9LoUApSibAHxVgS1UrAxdfqpJpoatR5yXh/SpH++4QGTs6n824b2LNmDFO8XAhVWCvIcbU61ssCtFyGtvbahnj4T7WlZLVHzg4S7B+e492KXGDuEQ3DuS48Y3rylcMavvnEgal9JRM3hVZzBq4XI90v/ZYFeSXy9CkzvcsvzLxpaC9M6yR0WkqDCAM2mfbIAnOfL61X4fvjo=
  file: build/libs/hello-world-1.0.jar
  on:
    repo: newmanshee/hello-world
    tags: true
    all_branches: true
env:
  global:
    secure: OuuYJjprVRK1ZyxsL4bcWr4z2RxneuHBjOWjiZPvGQHHK3yn5kSWxmUErAOU47QdoTcM0ojVCfig0HGUqk+IwaHQmFqpWcR8N0JkijDinRM9Cc34uub4HBZEOoXqL0JYcWUm29IDiBn6ets8rXuFzoXYPvoMd1amdjfvVI7YNTkiBeumQUwHdeadA+F5a1YdX/HflBHYof90b44GlraSvW+2R+x7ErHBnX94+41v8N6yb6mJz7QceWVK0qLUj0mzVFC2TTivySDyT7ikoEdi3omDagldabsmAJM/jo885hF1yAz4/guDhWpUrcjHCHYI0cL5youynmbrmj7LecsgvrTXGl1ScYvngKZTU6T5G49g4qNO0dT/9gJMS3cnPay8AGXnTFQLUFE5sANi4bjdCWjNUylGPgm5Bwd3TBT4NJ+bZ3Bs3aNNhTibJUSz6m7dyS+Z94qgqor14mydO2gJmEyVbyRy4oza2gxSItbus9RtayupKc8NsJfgDT56opiswDk5oxEWJK2FLvh5G5bBxNkkXmFRGxv7TypOMLe9nPMcpETVIdFP7YVu8OTH6OPkuyT7J2SqrVT7kgiQ/RlOpTZXyQ9EmYW76jcWDkaAHs8pLoFoNRC5NlCA8mwKS701/Ft1ubueLvevm63PIQOWlUIqXGZws0L9uEHKgnvOS+E=
