language: java
install: gradle -v build
script: gradle build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VCvrzkhwBNMgO+EJiQ0uRmUP4rsupdeRQ1fAJV2gJB/0pOauygrXBv9AMVLCZWN5JzytzuMj+vfWZKLD4HlugPR/GBmBOfpBBQxsSSOCzvNd7avrgdY559TGaw4SaGhx8x37rbNXV8JISgm2PAUwpbV8azql/NSuWqDDwqkmhgyn8AXmh/s+a1swnf7Aa+65NMWsh1GDKrPDgfe1mM/ol3AZ/MVBjaJYorz2izktd0WoB5RHrDWocR0KJ9lg+DpfgSuLwakFkbc2S1j3T+pRIOI7sP4QZxmnT1NHELt8QCPrRvUYrFSkge/AhVZ98XwjO63MamVNyg94cYueGQ2RE9ky7e5yAFwt3Wl7AJi4BYi3qLHkIfLZDdj5GzPu8DGDXmgovpkGJQYzYQEFItDWic5T6bDjZA47DtrFQTdkGe1emXV2wLeyp795N0OO4AGry/qtkfoBF4i5ZUXGEjQcdij/g7m+Hda9LoUApSibAHxVgS1UrAxdfqpJpoatR5yXh/SpH++4QGTs6n824b2LNmDFO8XAhVWCvIcbU61ssCtFyGtvbahnj4T7WlZLVHzg4S7B+e492KXGDuEQ3DuS48Y3rylcMavvnEgal9JRM3hVZzBq4XI90v/ZYFeSXy9CkzvcsvzLxpaC9M6yR0WkqDCAM2mfbIAnOfL61X4fvjo=
  file: build/libs/hello-world-1.0.jar
  on:
    repo: newmanshee/hello-world
#    tags: true
    all_branches: true
