language: java
install: gradle -v build
 before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "newmanshee"
      - git config --local user.email "newman_shee@hotmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: d7af1af80328aa341e580da15bbf681ac1e21565
  file: build/libs/hello-world-1.0.jar
  skip_cleanup: true
  on:
    tags: true
script: gradle test jacocoTestReport 
after_success:
  - gradle coveralls
